# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

def config_valid_archs(config)
  valid_archs = %W[arm64 arm64e]
  if config.name == 'Debug'
    valid_archs << 'x86_64'
  end
  config.build_settings['VALID_ARCHS'] = valid_archs.join(' ')
  if config.name == 'Debug'
    config.build_settings['VALID_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
  end
end

def add_simulator_arch(project)
  require 'xcodeproj'
  xcproject = Xcodeproj::Project.open(project)
  xcproject.native_targets.each do |target|
    target.build_configurations.each do |configuration|
      config_valid_archs(configuration)
    end
  end
  xcproject.save
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  add_simulator_arch("./Runner.xcodeproj")
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config_valid_archs(config) 
  end
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config_valid_archs(config) 
    end
  end
  installer.pods_project.save
end

