//
// Created by yhtree on 2022/4/15.
//

#ifndef KRAKENBRIDGE_CORE_HTML_HTML_BASE_ELEMENT_H_
#define KRAKENBRIDGE_CORE_HTML_HTML_BASE_ELEMENT_H_

class html_base_element {};

#endif  // KRAKENBRIDGE_CORE_HTML_HTML_BASE_ELEMENT_H_
