import './console';
import './websocket';
import './fetch';
import './document';
import './match-media';
import './location';
import './navigator';
import './xhr';
import './window';
import './blob';
import './async-storage';
import './url-search-params';
import './url';
import './module-listener'
import './performance';
import './kraken';
