#!/usr/bin/env bash

BUILDPATH="$( cd "$(dirname "$0")" ; pwd -P )"
KRAKEN_LIBRARY_PATH=$BUILDPATH/lib
KRAKEN_BUNDLE_PATH=$BUILDPATH/bundle.js

file="$PWD/$1"

if [ -f $file ]
then
  echo "Start JavaScript bundle with Kraken: $1"
  KRAKEN_BUNDLE_PATH=$file
  export KRAKEN_LIBRARY_PATH
  export KRAKEN_BUNDLE_PATH

  if [[ "$OSTYPE" == 'linux-gnu' ]]; then
    $BUILDPATH/app/kraken
  elif [[ "$OSTYPE" == "darwin" ]]; then
    $BUILDPATH/app/Kraken.app/Contents/MacOS/Kraken
  fi
else
  echo "ERROR: not found file $file"
  exit 1
fi

