name: kraken_sdk_module
description: Module for build sdk frameworks.
version: 0.7.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kraken: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  kraken:
    path: ../kraken

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  module:
    androidX: true
    androidPackage: com.openkraken.kraken.sdk
    iosBundleIdentifier: com.openkraken.kraken.sdk
